package petweb;

/*
 * Тестовое задание для Вадима
 */

import java.util.Date;

/**
 * Pets generated by hbm2java
 */
public class Pets  implements java.io.Serializable {


     private String nickname;
     private String speciesName;
     private Date birthdate;
     private boolean male;
     private String owner;

    public Pets() {
    }

    public Pets(String nickname, String speciesName, Date birthdate, boolean male, String owner) {
       this.nickname = nickname;
       this.speciesName = speciesName;
       this.birthdate = birthdate;
       this.male = male;
       this.owner = owner;
    }
   
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getSpeciesName() {
        return this.speciesName;
    }
    
    public void setSpeciesName(String speciesName) {
        this.speciesName = speciesName;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public boolean isMale() {
        return this.male;
    }
    
    public void setMale(boolean male) {
        this.male = male;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }




}


