/*
 * Тестовое задание для Вадима
 */
package petweb;



/**
 * Species generated by hbm2java
 */
public class Species  implements java.io.Serializable {


     private String name;

    public Species() {
    }

    public Species(String name) {
       this.name = name;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


